### ISSUE TITLE
Bug found in Apple flinger game when language is changed in game settings  

### ISSUE THREAD

**Issue by jubreal** [ar-/apple-flinger#1]
#### Expected behavior
Game language should change to the newly selected language and the game should keep running. 

#### Actual behavior
The game closes immediately by itself after a language is selected from the language options. 

#### How to reproduce
1. Download the app here[https://play.google.com/store/apps/details?id=com.ardash.appleflinger.android]
2. Launch the app
3. Click on the globe (language) icon
4. Select any language.
Device used : Infinix Note 3 (x601) *Operating system: Android version 6.0 *App version :1.4.6

#### Recording Of The Bug
https://youtu.be/_Ova7M2eNMw
    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@jubreal/bug-found-in-apple-flinger-game">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by ar-** [comment]
Hi I'm closing this, because:

1. Bugs have to be raised in the main repo on Gitlab. This is just the mirror, so the people have more choices to download the code from somewhere. pull requests can also be done here, but I'd merge them remotely. I don't have the resources to follow, merge and maintain 2 bugtrackers. Also I'm not receiving the emails of github.
2. The language selection has been improved with the fix of https://gitlab.com/ar-/apple-flinger/issues/56 . But generally this is not a crash. It is a well planned System.exit() call. The application has to restart, because some languages need another font-type. And the font type has to be reloaded and re-rendered , when the app starts. There is currently no technical possibility to switch ad-hoc.
3. The app is not crashing, and not simply exiting. It is actually being restarted. I'm testing that, for Android 4 to Android 8. If you try this with the latest version and it is still not working, please create an issue on gitlab.
4. I generally disagree with bounty schemes (like Utopian), to pay someone for a trivial feature or bugfix. As long as I'm maintaining this app, it will be 100% free. I have a bit the feeling, that issue was only raised here on github, because Utopian didn't support gitlab at the tie of the creation yet. And that case, this is spam. ...... And yeah, even if I would support a bounty scheme, it certainly wouldn't be Utopian!
